#[target.x86_64-unknown-linux-gnu]
#rustflags = [
#    #"-C", "link-arg=-fuse-ld=lld",
#    "-C", "link-arg=-fuse-ld=mold",
#]

[package]
name = "logic_simulator"
version = "0.1.0"
edition = "2021"
autotests = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]

# Very expensive, but makes 
# code a tiny bit faster:
#lto = true
#codegen-units = 1
#panic = "abort"


opt-level = 3

#rustflags = "-C llvm-args=\"-unroll-threshold=1000\""
#rustflags = "-C target-cpu=native"
debug = 1
[rust]
debuginfo-level = 1

#[lib]
#test = true
#path = "src/lib.rs"

[dependencies]
base64 = {version = "0.13.0"}
zstd = {version = "0.11", default-features = false}
colored = {version = "2.0.0", default-features = false}
#rayon = "*"
#bitvec = "1"
itertools = "0.10.5"


[dev-dependencies]
criterion = {version = "0.3", default-features = false}
pretty_assertions = "1.3.0"


[[bench]]
name = "benchmark"
harness = false
