[package]
name = "logic_simulator"
version = "0.1.0"
edition = "2021"
autotests = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

debug = 1
[rust]
debuginfo-level = 1

#[lib]
#test = true
#path = "src/lib.rs"

[dependencies]
base64 = "0.13.0"
zstd = "0.11"
colored = "2.0.0"
rayon = "*"
#bitvec = "1"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
