#array_width = 60
#attr_fn_like_width = 70
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
#chain_width = 60
#color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
fn_args_layout = "Tall"
#fn_call_width = 60
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
#max_width = 100
merge_derives = true
imports_granularity = "Module"
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
#short_array_element_width_threshold = 10
#single_line_if_else_max_width = 50
#struct_lit_width = 18
#struct_variant_width 35
tab_spaces = 4
use_field_init_shorthand = false
use_try_shorthand = true
